version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - app_network
    # We don't expose 5000 to host machine since Nginx will proxy

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge